### PR TITLE
Added Android Dev Summit 2022 notes

### PR DESCRIPTION
**Pull request by mksiddiq**
## What type of PR is this? (check all applicable)

- [ ] 🚀 Added Name
- [ ] ✨ Feature
- [x] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [ ] 🚩 Other

### CODE REVIEW

**Review by AndroidLion48 — COMMENTED** [review]
Awesome Summary! Thanks for participating and sharing your views!

**Review by AndroidLion48 — APPROVED** [review]

**Comment by mksiddiq** [comment]
@AndroidLion48 Thank you so much :D

**Comment by mksiddiq** [comment]
@Tc2r1 @AndroidLion48 Is this repo removed from hacktoberfest?? It shows excluded in my hacktoberfest account :(

**Comment by Tc2r1** [comment]
@mksiddiq can you get on hangouts?

**Comment by mksiddiq** [comment]
Yeah sure

**Pull request merged**
