### PR TITLE
Added ROOM database for question and answers with dao and entity in database package of kotlin retrofit. Also added my name in contributors list.

### PR DESCRIPTION
**Pull request by mksiddiq**
## What type of PR is this? (check all applicable)

- [x] 🚀 Added Name
- [x] ✨ Feature
- [ ] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [ ] 🚩 Other

### CODE REVIEW

**Comment by Tc2r1** [comment]
Although this requires some changes, this makes me happy, Omega good job!

**Comment by mksiddiq** [comment]
Hi, glad you liked the effort. What changes are to be made? Is it eligible to be merged right now?

**Comment by mksiddiq** [comment]
@Tc2r1 I have also made the splash screen. But I am unable to push and merge until room PR is merged first.

**Comment by Tc2r1** [comment]
> @Tc2r1 I have also made the splash screen. But I am unable to push and merge until room PR is merged first.

First, I have cleaned up the Json for you so the app will now crash on load. 

Second, please make a seperate branch for each of your changes, don't always commit to "master".

As a professional, you should try hard never to commit to master, you branch off of master, then make your changes, then create a PR. This way you can work on more than one thing at a time :D

LMK if you need help (Let me know).

**Comment by mksiddiq** [comment]
Thank you so much for letting me know. I did not know much about branches. I will now take care about these things in future :D

**Comment by Tc2r1** [comment]
@mksiddiq join me for discussion i'll only be up for about 30 min though. https://8x8.vc/tc2r1

**Pull request closed without merging**
