### PR TITLE
added comments to various files in kotlin folder

### PR DESCRIPTION
**Pull request by mksiddiq**
## What type of PR is this? (check all applicable)

- [ ] 🚀 Added Name
- [ ] ✨ Feature
- [x] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [x] 📝 Documentation Update
- [ ] 🚩 Other

### CODE REVIEW

**Comment by Tc2r1** [comment]
@mksiddiq  Nice job, I think you have the skills to take on an issue that requires code ^_^ I saw your linked in, up for it?

**Comment by mksiddiq** [comment]
> @mksiddiq Nice job, I think you have the skills to take on an issue that requires code ^_^ I saw your linked in, up for it?
@Tc2r1 Thank you so much. Glad you liked it! Yes I am totally up for some code work in native Kotlin :)

**Comment by Tc2r1** [comment]
@mksiddiq  Please take a look at the issues available. We've designed this project so each issue can be done several times over (in different modules) as well as allowing for you to create a module of your own (by duplicating the template folder) and building the app in your own version. There are several pages of issues to choose from with a variety of difficulties.

**Review by Tc2r1 — APPROVED** [review]

**Comment by mksiddiq** [comment]
Sure, I will see all the issues and will definitely work on those that I can resolve! I have filled the check marks. Thank you :)

**Pull request merged**
