### PR TITLE
SplashScreen that support for Android 12.

### PR DESCRIPTION
**Pull request by Rarj**
## What type of PR is this? (check all applicable)

- [ ] 🚀 Added Name
- [x] ✨ Feature
- [x] 🌟 stared the repo
- [ ] 🐛 Grammatical Error
- [ ] 📝 Documentation Update
- [ ] 🚩 Other

## Description
I added SplashScreen feature using best practice that support for Android 12.

## Add Link of GitHub Profile
https://github.com/Rarj/Hacktoberfest_Interview_App

## Screenshot
Tested on Android Q (API 29)

## Attribute Image
<a href="https://www.freepik.com/free-vector/taking-notes-concept-illustration_7069574.htm#query=interview&position=4&from_view=search&track=sph#page=1&query=i&from_query=undefined&position=0&from_view=search&track=sph">Image by storyset</a> on Freepik

### CODE REVIEW

**Review by Tc2r1 — APPROVED** [review]

**Comment by prasad-333** [comment]
Looks this PR is breaking the build for ic_logo_foreground which is not committed or assigned wrongly from available asset.

**Comment by Tc2r1** [comment]
@Rarj  @prasad-333  if you want to fix it, do so and create a PR? Thanks :)

**Comment by Tc2r1** [comment]
@Rarj  I am marking this as spam and invalid due to the fact that it doesn't build, is missing key factors and goes against the contribution guide. 

If you wish for me to remove these labels, please update (and fix) your code  and create a new pull request.

**Comment by Rarj** [comment]
hi @Tc2r1 , I will check and fix it ASAP.

**Comment by Tc2r1** [comment]
@Rarj I've just spent the last hour repairing the project. I am willing to remove the label if you will create a fragment that lets users select which quiz they will do, Integrating these changes so that they can build quizzes for python or other languages. https://github.com/Tc2r1/Hacktoberfest_Interview_App/pull/167

**Pull request merged**
